// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/todo.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateTodoRequest struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Completed            bool     `protobuf:"varint,2,opt,name=completed,proto3" json:"completed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTodoRequest) Reset()         { *m = CreateTodoRequest{} }
func (m *CreateTodoRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTodoRequest) ProtoMessage()    {}
func (*CreateTodoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d28b1ccc7160a78f, []int{0}
}

func (m *CreateTodoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTodoRequest.Unmarshal(m, b)
}
func (m *CreateTodoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTodoRequest.Marshal(b, m, deterministic)
}
func (m *CreateTodoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTodoRequest.Merge(m, src)
}
func (m *CreateTodoRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTodoRequest.Size(m)
}
func (m *CreateTodoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTodoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTodoRequest proto.InternalMessageInfo

func (m *CreateTodoRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CreateTodoRequest) GetCompleted() bool {
	if m != nil {
		return m.Completed
	}
	return false
}

type CreateTodoResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Completed            bool     `protobuf:"varint,3,opt,name=completed,proto3" json:"completed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTodoResponse) Reset()         { *m = CreateTodoResponse{} }
func (m *CreateTodoResponse) String() string { return proto.CompactTextString(m) }
func (*CreateTodoResponse) ProtoMessage()    {}
func (*CreateTodoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d28b1ccc7160a78f, []int{1}
}

func (m *CreateTodoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTodoResponse.Unmarshal(m, b)
}
func (m *CreateTodoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTodoResponse.Marshal(b, m, deterministic)
}
func (m *CreateTodoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTodoResponse.Merge(m, src)
}
func (m *CreateTodoResponse) XXX_Size() int {
	return xxx_messageInfo_CreateTodoResponse.Size(m)
}
func (m *CreateTodoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTodoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTodoResponse proto.InternalMessageInfo

func (m *CreateTodoResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CreateTodoResponse) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CreateTodoResponse) GetCompleted() bool {
	if m != nil {
		return m.Completed
	}
	return false
}

type GetTodosRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTodosRequest) Reset()         { *m = GetTodosRequest{} }
func (m *GetTodosRequest) String() string { return proto.CompactTextString(m) }
func (*GetTodosRequest) ProtoMessage()    {}
func (*GetTodosRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d28b1ccc7160a78f, []int{2}
}

func (m *GetTodosRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTodosRequest.Unmarshal(m, b)
}
func (m *GetTodosRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTodosRequest.Marshal(b, m, deterministic)
}
func (m *GetTodosRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTodosRequest.Merge(m, src)
}
func (m *GetTodosRequest) XXX_Size() int {
	return xxx_messageInfo_GetTodosRequest.Size(m)
}
func (m *GetTodosRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTodosRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTodosRequest proto.InternalMessageInfo

type GetTodosResponse struct {
	TodoList             []*GetTodosResponse_Todo `protobuf:"bytes,1,rep,name=todo_list,json=todoList,proto3" json:"todo_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *GetTodosResponse) Reset()         { *m = GetTodosResponse{} }
func (m *GetTodosResponse) String() string { return proto.CompactTextString(m) }
func (*GetTodosResponse) ProtoMessage()    {}
func (*GetTodosResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d28b1ccc7160a78f, []int{3}
}

func (m *GetTodosResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTodosResponse.Unmarshal(m, b)
}
func (m *GetTodosResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTodosResponse.Marshal(b, m, deterministic)
}
func (m *GetTodosResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTodosResponse.Merge(m, src)
}
func (m *GetTodosResponse) XXX_Size() int {
	return xxx_messageInfo_GetTodosResponse.Size(m)
}
func (m *GetTodosResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTodosResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTodosResponse proto.InternalMessageInfo

func (m *GetTodosResponse) GetTodoList() []*GetTodosResponse_Todo {
	if m != nil {
		return m.TodoList
	}
	return nil
}

type GetTodosResponse_Todo struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Completed            bool     `protobuf:"varint,3,opt,name=completed,proto3" json:"completed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTodosResponse_Todo) Reset()         { *m = GetTodosResponse_Todo{} }
func (m *GetTodosResponse_Todo) String() string { return proto.CompactTextString(m) }
func (*GetTodosResponse_Todo) ProtoMessage()    {}
func (*GetTodosResponse_Todo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d28b1ccc7160a78f, []int{3, 0}
}

func (m *GetTodosResponse_Todo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTodosResponse_Todo.Unmarshal(m, b)
}
func (m *GetTodosResponse_Todo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTodosResponse_Todo.Marshal(b, m, deterministic)
}
func (m *GetTodosResponse_Todo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTodosResponse_Todo.Merge(m, src)
}
func (m *GetTodosResponse_Todo) XXX_Size() int {
	return xxx_messageInfo_GetTodosResponse_Todo.Size(m)
}
func (m *GetTodosResponse_Todo) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTodosResponse_Todo.DiscardUnknown(m)
}

var xxx_messageInfo_GetTodosResponse_Todo proto.InternalMessageInfo

func (m *GetTodosResponse_Todo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetTodosResponse_Todo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *GetTodosResponse_Todo) GetCompleted() bool {
	if m != nil {
		return m.Completed
	}
	return false
}

type UpdateTodoRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Completed            bool     `protobuf:"varint,3,opt,name=completed,proto3" json:"completed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTodoRequest) Reset()         { *m = UpdateTodoRequest{} }
func (m *UpdateTodoRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateTodoRequest) ProtoMessage()    {}
func (*UpdateTodoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d28b1ccc7160a78f, []int{4}
}

func (m *UpdateTodoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTodoRequest.Unmarshal(m, b)
}
func (m *UpdateTodoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTodoRequest.Marshal(b, m, deterministic)
}
func (m *UpdateTodoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTodoRequest.Merge(m, src)
}
func (m *UpdateTodoRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateTodoRequest.Size(m)
}
func (m *UpdateTodoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTodoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTodoRequest proto.InternalMessageInfo

func (m *UpdateTodoRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateTodoRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *UpdateTodoRequest) GetCompleted() bool {
	if m != nil {
		return m.Completed
	}
	return false
}

type UpdateTodoResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Completed            bool     `protobuf:"varint,3,opt,name=completed,proto3" json:"completed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTodoResponse) Reset()         { *m = UpdateTodoResponse{} }
func (m *UpdateTodoResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateTodoResponse) ProtoMessage()    {}
func (*UpdateTodoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d28b1ccc7160a78f, []int{5}
}

func (m *UpdateTodoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTodoResponse.Unmarshal(m, b)
}
func (m *UpdateTodoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTodoResponse.Marshal(b, m, deterministic)
}
func (m *UpdateTodoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTodoResponse.Merge(m, src)
}
func (m *UpdateTodoResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateTodoResponse.Size(m)
}
func (m *UpdateTodoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTodoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTodoResponse proto.InternalMessageInfo

func (m *UpdateTodoResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateTodoResponse) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *UpdateTodoResponse) GetCompleted() bool {
	if m != nil {
		return m.Completed
	}
	return false
}

type DeleteTodoRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTodoRequest) Reset()         { *m = DeleteTodoRequest{} }
func (m *DeleteTodoRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteTodoRequest) ProtoMessage()    {}
func (*DeleteTodoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d28b1ccc7160a78f, []int{6}
}

func (m *DeleteTodoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTodoRequest.Unmarshal(m, b)
}
func (m *DeleteTodoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTodoRequest.Marshal(b, m, deterministic)
}
func (m *DeleteTodoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTodoRequest.Merge(m, src)
}
func (m *DeleteTodoRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteTodoRequest.Size(m)
}
func (m *DeleteTodoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTodoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTodoRequest proto.InternalMessageInfo

func (m *DeleteTodoRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteTodoResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTodoResponse) Reset()         { *m = DeleteTodoResponse{} }
func (m *DeleteTodoResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteTodoResponse) ProtoMessage()    {}
func (*DeleteTodoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d28b1ccc7160a78f, []int{7}
}

func (m *DeleteTodoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTodoResponse.Unmarshal(m, b)
}
func (m *DeleteTodoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTodoResponse.Marshal(b, m, deterministic)
}
func (m *DeleteTodoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTodoResponse.Merge(m, src)
}
func (m *DeleteTodoResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteTodoResponse.Size(m)
}
func (m *DeleteTodoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTodoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTodoResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CreateTodoRequest)(nil), "todo.CreateTodoRequest")
	proto.RegisterType((*CreateTodoResponse)(nil), "todo.CreateTodoResponse")
	proto.RegisterType((*GetTodosRequest)(nil), "todo.GetTodosRequest")
	proto.RegisterType((*GetTodosResponse)(nil), "todo.GetTodosResponse")
	proto.RegisterType((*GetTodosResponse_Todo)(nil), "todo.GetTodosResponse.Todo")
	proto.RegisterType((*UpdateTodoRequest)(nil), "todo.UpdateTodoRequest")
	proto.RegisterType((*UpdateTodoResponse)(nil), "todo.UpdateTodoResponse")
	proto.RegisterType((*DeleteTodoRequest)(nil), "todo.DeleteTodoRequest")
	proto.RegisterType((*DeleteTodoResponse)(nil), "todo.DeleteTodoResponse")
}

func init() {
	proto.RegisterFile("proto/todo.proto", fileDescriptor_d28b1ccc7160a78f)
}

var fileDescriptor_d28b1ccc7160a78f = []byte{
	// 352 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0x41, 0x4f, 0xc2, 0x30,
	0x14, 0xc7, 0xb3, 0x81, 0x06, 0x1e, 0x89, 0xb2, 0x06, 0x75, 0x41, 0x0f, 0x64, 0x5e, 0x38, 0xc8,
	0x96, 0xe0, 0x45, 0x4f, 0x24, 0x6a, 0x42, 0x62, 0x3c, 0x4d, 0x8d, 0xc4, 0x8b, 0x19, 0xeb, 0x13,
	0x9b, 0x00, 0xad, 0x6d, 0xf1, 0x4b, 0xf8, 0x05, 0xfc, 0xb8, 0xa6, 0x1b, 0x4b, 0xc9, 0x86, 0x9e,
	0x38, 0xed, 0xed, 0xb5, 0xfd, 0xfd, 0xdf, 0xfb, 0xbf, 0x16, 0xda, 0x42, 0x72, 0xcd, 0x23, 0xcd,
	0x29, 0x0f, 0xb3, 0x90, 0xd4, 0x4d, 0x1c, 0x8c, 0xc1, 0xbb, 0x95, 0x98, 0x68, 0x7c, 0xe2, 0x94,
	0xc7, 0xf8, 0xb9, 0x42, 0xa5, 0x49, 0x07, 0xf6, 0x34, 0xd3, 0x73, 0xf4, 0x9d, 0x9e, 0xd3, 0x6f,
	0xc6, 0xf9, 0x0f, 0x39, 0x83, 0x66, 0xca, 0x17, 0x62, 0x8e, 0x1a, 0xa9, 0xef, 0xf6, 0x9c, 0x7e,
	0x23, 0xb6, 0x89, 0x60, 0x02, 0x64, 0x13, 0xa4, 0x04, 0x5f, 0x2a, 0x24, 0x07, 0xe0, 0x32, 0x9a,
	0x61, 0x6a, 0xb1, 0xcb, 0xa8, 0x25, 0xbb, 0x7f, 0x92, 0x6b, 0x65, 0xb2, 0x07, 0x87, 0x63, 0xd4,
	0x06, 0xab, 0xd6, 0x05, 0x06, 0x3f, 0x0e, 0xb4, 0x6d, 0x6e, 0xad, 0x75, 0x05, 0x4d, 0xd3, 0xd2,
	0xdb, 0x9c, 0x29, 0xed, 0x3b, 0xbd, 0x5a, 0xbf, 0x35, 0x3c, 0x0d, 0xb3, 0x86, 0xcb, 0x5b, 0xc3,
	0xac, 0xc6, 0x86, 0x59, 0x7b, 0x60, 0x4a, 0x77, 0xef, 0xa1, 0x6e, 0x32, 0x3b, 0xa9, 0xf6, 0x05,
	0xbc, 0x67, 0x41, 0x4b, 0x86, 0xee, 0x02, 0x3c, 0x01, 0xb2, 0x09, 0xde, 0xa1, 0xc1, 0xe7, 0xe0,
	0xdd, 0xa1, 0x09, 0xff, 0x29, 0x39, 0xe8, 0x00, 0xd9, 0xdc, 0x94, 0xcb, 0x0f, 0xbf, 0x5d, 0x68,
	0x99, 0xc4, 0x23, 0xca, 0x2f, 0x96, 0x22, 0x19, 0x01, 0xd8, 0x5b, 0x40, 0x4e, 0x72, 0xfb, 0x2b,
	0x17, 0xac, 0xeb, 0x57, 0x17, 0xd6, 0xfd, 0x5c, 0x43, 0xa3, 0x98, 0x16, 0x39, 0x2a, 0x4f, 0x2f,
	0x3f, 0x7c, 0xbc, 0x7d, 0xa8, 0x46, 0xdb, 0x1a, 0x54, 0x68, 0x57, 0x66, 0x51, 0x68, 0x6f, 0xf1,
	0x72, 0x04, 0x60, 0x5b, 0x2c, 0x00, 0x15, 0x67, 0x0a, 0x40, 0xd5, 0x8d, 0x9b, 0xf0, 0xf5, 0x62,
	0xc6, 0xf4, 0xc7, 0x6a, 0x1a, 0xa6, 0x7c, 0x11, 0x31, 0xf9, 0x9e, 0x2c, 0x07, 0x89, 0x94, 0x5c,
	0x31, 0x1a, 0xcd, 0xa4, 0x48, 0x07, 0xe6, 0xe0, 0x20, 0x11, 0x22, 0xca, 0x9e, 0xe0, 0x74, 0x3f,
	0xfb, 0x5c, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0x45, 0x91, 0x50, 0x9b, 0x9d, 0x03, 0x00, 0x00,
}